# Backend is generated by Terragrunt (stages/terragrunt.hcl -> backend_generated.tf):
# a local backend keyed at .tfstate/<env>/cluster/terraform.tfstate.
#
# This layer's state holds only cluster/topology facts (no secrets). For a team,
# switch to a remote, locking, encrypted backend in the root stages/terragrunt.hcl
# remote_state block — see terraform/bootstrap/backend.tf for the worked example.
