# Backend is generated by Terragrunt (stages/terragrunt.hcl -> backend_generated.tf):
# a local backend keyed at .tfstate/<env>/bootstrap/terraform.tfstate.
#
# This layer's state holds no plaintext secrets (only object references), but for
# a team switch to a remote, locking, encrypted backend. Example (set in the
# root stages/terragrunt.hcl remote_state block instead of here):
#
#   remote_state {
#     backend = "s3"
#     config = {
#       bucket       = "platform-tfstate"
#       key          = "platform/${path_relative_to_include()}.tfstate"
#       region       = "eu-west-1"
#       encrypt      = true
#       use_lockfile = true   # native S3 state locking (OpenTofu 1.10+)
#     }
#   }
