apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
  labels:
    {{- include "secret-store.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.path | quote }}
      version: {{ .Values.vault.version }}
      auth:
        # Least privilege: this token can only read platform/db/* (see TF vault-config
        # eso_policy). It is written by the TF services layer, never committed.
        tokenSecretRef:
          name: {{ .Values.vault.tokenSecretRef.name }}
          namespace: {{ .Values.vault.tokenSecretRef.namespace }}
          key: {{ .Values.vault.tokenSecretRef.key }}
