# Backend is generated by Terragrunt (stages/terragrunt.hcl -> backend_generated.tf):
# a local backend keyed at .tfstate/<env>/services/terraform.tfstate.
#
# WARNING: this layer's state DOES contain sensitive material (generated DB
# passwords and the ESO Vault token). For any shared/non-sandbox use you MUST use
# a remote, encrypted, locking backend and restrict access to it — configure it in
# the root stages/terragrunt.hcl remote_state block (s3 with encrypt + kms_key_id
# + use_lockfile), not here.
